services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  ms-auth:
    build: ./backend/ms-auth
    ports:
      - "8088:8088"

  ms-clientes:
    build: ./backend/ms-clientes
    ports:
      - "8086:8086"

  ms-flota-rest:
    build: ./backend/ms-flota-rest
    ports:
      - "8081:8081"

  ms-taller-soap:
    build: ./backend/ms-taller-soap
    ports:
      - "8089:8089"

  ms-pedidos:
    build: ./backend/ms-pedidos
    ports:
      - "8087:8087"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq

  ms-ruteo:
    build: ./backend/ms-ruteo
    ports:
      - "8082:8082"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      FLEET_SERVICE_URL: http://ms-flota-rest:8081/api/vehicles/available
    depends_on:
      - rabbitmq
      - ms-flota-rest

  ms-seguimiento:
    build: ./backend/ms-seguimiento
    ports:
      - "8083:8083"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq

  ms-facturacion:
    build: ./backend/ms-facturacion
    ports:
      - "8084:8084"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq

  ms-notificaciones:
    build: ./backend/ms-notificaciones
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq

  graphql-gateway:
    build: ./backend/graphql-gateway
    ports:
      - "8080:8080"
    environment:
      SERVICES_ORDERS_URL: http://ms-pedidos:8087/api/orders
      SERVICES_SHIPMENTS_URL: http://ms-ruteo:8082/api/shipments
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
      - ms-pedidos
      - ms-ruteo
