sonar.projectName=LogiFlow Phase 1
sonar.sourceEncoding=UTF-8

sonar.sources=backend/ms-flota-rest/src/main/java,backend/ms-taller-soap/src/main/java
sonar.tests=backend/ms-flota-rest/src/test/java,backend/ms-taller-soap/src/test/java
sonar.java.binaries=backend/ms-flota-rest/target/classes,backend/ms-taller-soap/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/ms-flota-rest/target/site/jacoco/jacoco.xml,backend/ms-taller-soap/target/site/jacoco/jacoco.xml

sonar.exclusions=frontend/**,infrastructure/**,**/target/**,**/.idea/**
sonar.test.exclusions=frontend/**
