spring.application.name=ms-notificaciones
server.port=8085

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# No Database needed for this microservice as it only logs
spring.datasource.url=jdbc:h2:mem:notifdb
spring.jpa.hibernate.ddl-auto=update
