spring.application.name=ms-ruteo
server.port=8082

# Internal Services URLs
fleet.service.url=http://localhost:8081/api/vehicles/available

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Database Configuration (H2 for local dev)
spring.datasource.url=jdbc:h2:mem:ruteodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
