spring.application.name=ms-ruteo
server.port=8082
fleet.service.url=${FLEET_SERVICE_URL:http://localhost:8081/api/vehicles/available}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ruteodb}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html