spring.application.name=ms-seguimiento
server.port=8083

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Database Configuration (H2 for local dev if needed)
spring.datasource.url=jdbc:h2:mem:trackingdb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
