events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/auth {
            proxy_pass http://ms-auth:8088;
        }

        location /api/users {
            proxy_pass http://ms-auth:8088;
        }

        location /api/roles {
            proxy_pass http://ms-auth:8088;
        }

        location /api/clients {
            proxy_pass http://ms-clientes:8086;
        }

        location /api/vehicles {
            proxy_pass http://ms-flota-rest:8081;
        }

        location /api/drivers {
            proxy_pass http://ms-flota-rest:8081;
        }

        location /api/orders {
            proxy_pass http://ms-pedidos:8087;
        }

        location /api/shipments {
            proxy_pass http://ms-ruteo:8082;
        }

        location /api/invoices {
            proxy_pass http://ms-facturacion:8084;
        }

        location /api/maintenance {
            proxy_pass http://ms-taller:8089;
        }

        location /api/gateway {
            proxy_pass http://gateway:8080;
        }

        location /ws-tracking {
            proxy_pass http://ms-seguimiento:8083;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
        
    }
}
