events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/auth {
            proxy_pass http://ms-auth:8088/api/auth;
        }

        location /api/clients {
            proxy_pass http://ms-clientes:8086/api/clients;
        }

        location /api/corporate-accounts {
            proxy_pass http://ms-clientes:8086/api/corporate-accounts;
        }

        location /api/vehicles {
            proxy_pass http://ms-flota-rest:8081/api/vehicles;
        }

        location /api/drivers {
            proxy_pass http://ms-flota-rest:8081/api/drivers;
        }

        location /api/orders {
            proxy_pass http://ms-pedidos:8087/api/orders;
        }

        location /api/shipments {
            proxy_pass http://ms-ruteo:8082/api/shipments;
        }

        location /api/vehiculos {
            proxy_pass http://ms-taller-rest:8089/api/vehiculos;
        }

        location /api/mantenimientos {
            proxy_pass http://ms-taller-rest:8089/api/mantenimientos;
        }

        location /graphql {
            proxy_pass http://graphql-gateway:8080/graphql;
        }

        location /graphiql {
            proxy_pass http://graphql-gateway:8080/graphiql;
        }

        location /ws-tracking {
            proxy_pass http://ms-seguimiento:8083;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}