spring.application.name=graphql-gateway
server.port=8080

# Internal Microservices URLs
services.orders.url=http://localhost:8087/api/orders
services.shipments.url=http://localhost:8082/api/shipments

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# GraphQL Config
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
