spring.application.name=graphql-gateway
server.port=8080
services.orders.url=${ORDERS_SERVICE_URL:http://localhost:8087/api/orders}
services.shipments.url=${SHIPMENTS_SERVICE_URL:http://localhost:8082/api/shipments}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql