spring.application.name=ms-clientes
server.port=8086

# Database Configuration (H2 for local dev)
spring.datasource.url=jdbc:h2:mem:clientsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
